### ISSUE TITLE
Time slider stops moving after being dragged

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/website-3d-cell-viewer#280] opened 2024-07-03 17:57 UTC
## Description

Can get into a state where the time slider stops moving during playback.

## Expected Behavior

Time slider should move during playback.

## Reproduction

https://dev-aics-dtp-001.int.allencell.org/website-3d-cell-viewer/viewer?url=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2F%2Fassay-dev%2Fcomputational%2Fdata%2Fholistic%2Fendos%2Ffeasibility%2Fcdh5.ome.zarr

press play, the time slider moves. 

Then pause, then drag slider ahead, then press play. 

 **BUG** Slider no longer moves!!!

## Environment

Windows, Chrome

**Comment by ShrimpCryptid** [comment] 2024-07-03 23:29
Temporarily fixed by disabling memoization and built to production. Will need @frasercl to look at this when he gets back.

From debugging, I think the issue is that NouiSlider is considering itself "interacted with" and then stops syncing with the provided `start` value. We don't have direct control over the value it has selected, only the `start` field; normally, we change `start` as soon as we receive an `onChange` callback so the selected value + the `start` is always in sync. Then, if we change `start` again, NouiSlider considers itself still at the initial "default" state and changes its value to match the new `start` value.

![image](https://github.com/allen-cell-animated/website-3d-cell-viewer/assets/30200665/fd7e82d4-e62f-403b-a73d-2dfe0c8694a9)


It looks like an extra render is happening between after the `onChange` callback and before `onEnd` is called where the old value `start` value slips through... and then `NouiSlider` considers itself edited/interacted with and no longer returns to the `start` value when we change it.

**Comment by ShrimpCryptid** [comment] 2024-07-03 23:30
Validation for temporary fix: https://volumeviewer.allencell.org/viewer?url=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2F%2Fassay-dev%2Fcomputational%2Fdata%2Fholistic%2Fendos%2Ffeasibility%2Fcdh5.ome.zarr

**Comment by frasercl** [comment] 2024-07-03 23:55
This looks like a very reasonable interim fix - in fact, I'll have to verify whether the problem `SmarterSlider` was trying to solve still exists. It might be that the odd performance issues aren't with us anymore, or else aren't worth the odd bugs.

**Closed** 2024-07-11 21:20 UTC
Labels: bug, URGENT
